---
- name: 'Installing dependencies'
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates

- name: 'Adding APT key'
  become: yes
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 642AC823

- name: 'Adding APT repository'
  become: yes
  apt_repository:
    repo: deb https://dl.bintray.com/sbt/debian /
    state: present
    update_cache: yes

- name: 'Install SBT package'
  become: yes
  package:
    name: sbt
    state: latest
...